# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: phpload
  type: NodePort
  externalPort: 80
  internalPort: 80
  nodePort: 32288
replicaCount: 1
image:
  repository: phpload
  tag: 1.0.0
  pullPolicy: IfNotPresent
