apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "fullname" . }}-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ template "fullname" . }}
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
